### ISSUE TITLE
Is there a list?

### ISSUE THREAD

**Issue by nogweii** [CodeBrauer/100daysofcode#1]
Out of curiosity, do you have a planned list of projects? Or are you deciding a bit on-the-fly? Regardless, bravo and good luck!

**Comment by CodeBrauer** [comment]
There is a list of ideas what I could do - but I decide every evening what I do - because some days I don't have enough time for some bigger projects. But I think I will add them to the wiki :thinking:

**Comment by CodeBrauer** [comment]
I've created a wiki in this repository - more ideas will follow as I get home - the idea list is currently at my whiteboard (shame on me, there is the cloud for things like this)

https://github.com/CodeBrauer/100daysofcode/wiki
