### ISSUE TITLE
Hey, don't give up.

### ISSUE THREAD

**Issue by vadimadr** [CodeBrauer/100daysofcode#4]
There has been no new commits for more than 20 days. Don't throw away your dream in a halfway.

**Comment by rexpan** [comment]
Yeah, @CodeBrauer , please continue this project.

**Comment by CodeBrauer** [comment]
Yes - there are some projects in my pipeline that are not ready yet. I will push some code this weekend! 

Thanks for your support 😄  - Currently there is so much to do at work that it's hard to code more at home

**Comment by CodeBrauer** [comment]
There it is 😉
